### ISSUE TITLE
does not serve static directory correctly on windows

### ISSUE THREAD

**Issue by avisagie** [cortesi/devd#12]
I tried running devd purely to serve files in a directory under http://devd.io/static/, but could not get it to work. Looks like a bug to me.

Running devd 7bc137d6d on windows8, go1.5.1, 64-bit, git bash.

```
mkdir tmp
echo hello > tmp/hello.txt
bin/devd -p 8000 /static/=./tmp/
```

Then
```
curl http://devd.io:8000/static/hello.txt
```

Expected: prints hello.
Actual: 404 File not found
Curiously it also does not log the 404.

It works on linux and logs a 404 if I request something that is not there.

**Comment by cortesi** [comment]
Hmm... I've tried hard to reproduce this, with no luck. I don't have a Windows 8 box available, so there may be a platform difference between Windows 8 and 10 at play. The fact that the 404 is not logged, tells me that for some reason the route is not recognised at all - meaning that the issue is likely to lie on the left of the equals sign, rather than the right. 

Can you please try running with the --debug flag? Also, what happens when you run without a root prefix like so:

> devd ./tmp/

**Comment by avisagie** [comment]
Just `devd ./tmp/` works correctly.
I get no extra output with --debug.

However, some further experiments seem to suggest that it's specific to git bash:
* Running from the Windows command line (cmd.exe) works correctly. 
* So does running from cygwin.

**Comment by avisagie** [comment]
Found it. All git bash's fault.

I modified devd.go:main to print all the routes and os.Args. This is what I get:
```
$ bin/devd.exe --debug -H /static/=./tmp/
Routes (0)
Args (4)
   C:\Users\albert\Projects\devd\bin\devd.exe
   --debug
   -H
   C:/Program Files/Git/static/=./tmp/
```

Thanks for looking.

**Comment by clu--** [comment]
Hello,
  since you use devd under windows, could you help me with the correct syntax to serve a file, test.htm, located in z:\tmp\ (as you can see there's a drive letter, the path is not relative) so i could reach it with the localhost URL.
  thank you
J.Clu

**Comment by avisagie** [comment]
Either of the following seems to work correctly from the default Windows command prompt:
```
bin\devd.exe /tmp/=c:\tmp\
bin\devd.exe c:\tmp\
```
Then just visit http://dev.io/test.htm
