### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by tailhook** [cortesi/devd#17]
Since devd allows subdomains in some super-simple way. It would be nice to support CORS too. I believe that something like `--allow-cors` that allows every header and every method on `*` or `*.devd.io` (not sure what the best option is) would be good enough for development.

**Comment by cortesi** [comment]
Yes, a good suggestion! Will try to slip it in before the next release.

**Comment by simonewebdesign** [comment]
Any news?

**Comment by cortesi** [comment]
Have a look at the patch I just committed, and let me know if this hits the spot. The flag just sets the "Access-Control-Allow-Origin" header to *. We can't do better than that, because we can't specify a wildcard in specific origins, and even multiple origin listings are effectively unsupported by many browsers.

**Comment by simonewebdesign** [comment]
It looks good for our use case. Thank you!
