### ISSUE TITLE
one-line log output

### ISSUE THREAD

**Issue by brunobord** [cortesi/devd#20]
Hello,

``devd`` looks really great, so far, but I was wondering if it was possible to add an option to enable one-line log output. My use-cases:

What if I want to grep devd command line output to look after:

* the 404 or the 500 errors
* which .css files are loaded **and** see their different HTTP status

by just adding a "--one-line" option, one could filter out unwanted lines.

**Comment by simonewebdesign** [comment]
What's wrong with `grep`? It does exactly that.

For spotting 404 errors:

    devd | grep 404

For CSS files:

    devd | grep .css

**Comment by brunobord** [comment]
well, not really...

1 - Spotting 404

```
devd . 2>&1  | grep 404
<- 404 Not Found
```

You sureley know that there's a 404, but you don't know which resource is not found.

2 - Css (or whichever resource you want)

```
devd .  | grep css
14:08:05: GET /src/main/html/css/typography.css
14:08:05: GET /src/main/html/css/reset.css
14:08:05: GET /src/main/html/css/print.css
14:08:05: GET /src/main/html/css/screen.css
```

but *there* you don't have their status (200 or 304, or...)
The fact that the log is splitted in two distinct lines makes the grepping slightly more difficult than if it was just on one line.

**Comment by simonewebdesign** [comment]
Oh, I see what you mean. Agree with you, makes sense to have a `--one-line` option then, or even by default.

**Comment by marksteve** [comment]
You can use context control:
```
Context control:
  -B, --before-context=NUM  print NUM lines of leading context
  -A, --after-context=NUM   print NUM lines of trailing context
  -C, --context=NUM         print NUM lines of output context
```

```shell
devd ... | grep -B 1 404
```

**Comment by brunobord** [comment]
@marksteve I don't you're getting it. I think that a one-line log entry is a several-decade-old standard for servers and is the most convenient way to find information when it comes to debugging or compiling log data into another format (doing stats, or whatever)

**Comment by cortesi** [comment]
@brunobord I've intentionally broken away from one-line log entries with devd. The primary use case here is interactive - i.e. a developer looking at live terminal output. Given this, I made the decision to move to a less traditional log format with syntax colouring, and more information spread legibly over multiple lines. Yes, there's a tradeoff versus using a standard log format, but I think it's worth it.

That doesn't mean I don't want to make it easer to pick information out of verbose logs. The -I option is a step in that direction - it lets you ignore logs selectively to filter out things like static assets you might not be interested in. I would contemplate expanding that sort of filtering in a measured and modest way - maybe a grep-like positive filter that turns off logging for everything except for matches.

I'm closing this ticket, because I don't think a single-line log option is the way to tackle this, but if you have ideas for how to proceed, please keep the discussion going.
