### ISSUE TITLE
Ability to specify 404 page/handler

### ISSUE THREAD

**Issue by dsemke** [cortesi/devd#38]
For better or worse, I'm using [react-router](https://github.com/rackt/react-router) with [browserHistory](https://github.com/rackt/react-router/blob/master/docs/guides/basics/Histories.md#browserhistory) on a project which turns hash routes (`devd.io/#/foo`) into prettier urls (`devd.io/foo`). This functionality requires specific setup in the server software and I do not believe it is currently possible to configure devd to support this.

The recommended setup for nginx is to use the `try_files` directive to fall back on your react entry page if the file is not found (`try_files $uri /index.html`). I believe the simplest way to support this functionality in devd would be to allow for a 404 handler or fallback to be specified when the file server cannot find the specified resource. Perhaps a more robust way would be an extension to the routing syntax to allow for greater flexibility.

Thank you for your consideration

**Comment by cortesi** [comment]
I understand the motivation (I use react-router in some of my own projects), and I do think that this should be catered for in devd. The simplest solution would be to just add a global specification that maps all 404s to a specific route. Let's consider whether something more general would be better. Do you have a concrete idea of what a routing syntax extension for this would look like?

**Comment by dsemke** [comment]
Just brainstorming a bit, the global 404 handler would seem to break down when you have a multi-page app which would need to specify different react entry pages for different subtrees. With this in mind, maybe something like a `[subtree]!=[endpoint]` syntax could be used:

```bash
devd -ol . \
  /page2/!=./page2/index.html \
  !=./index.html # global handler (equivalent to /!=./index.html)
```
With such a syntax, any resource under `/page2/` that is not found is served `./page2/index.html`, all others are served `./index.html`.

I know shells tend to not like the `!` character, so this in particular might not work, but I think the general concept is simple enough to not over-complicate the tool but would still offer enough flexibility for these use cases.

**Comment by davidbilge** [comment]
This would also be useful for other js frameworks, e.g. angularjs.

**Comment by cortesi** [comment]
I've been pondering this issue, and I have a proposal to run past interested parties. What if we add a --404file argument to devd, which specifies a file to look for in the same directory if a file could not be found. You can then use something like "ln -s" to redirect this to index.html if needed, or serve up something entirely different.

This lets us serve the use case without a really complex override mechanism with a route specification. I've played with a specification mechanism that might work here, but haven't come up with anything very satisfactory.

**Comment by davidbilge** [comment]
I feel like this would not really help for the intended use case.

We use devd for angular development to "join" a local directory with a rest API on a remote system. What you want in this case is to serve an index.html file if no local file is found. But if the rest API serves a 404 this might be intended functionality. So, there needs to be at least a 404 handler for each route. 

About the ln -s idea: this would not work on windows systems. Also, it would be very tedious to create one symlink per directory.

**Comment by cortesi** [comment]
Hi David - to be clear, my proposal here is for the --404file mechanism to only affect local filesystem routes, which means that in your example the REST interface 404s will be left untouched. If you really wanted, you could specify "--404file index.html" to redirect all 404s to the index. We could aso slightly elaborate the scheme, and say that we'll search for an index over-ride file in parent directories up to the root of the route. I think this quite flexibly covers what is needed, and also leaves room for situations where, for instance, the index file and the 404 override differ. 

On windows (and in many use cases on all platforms) one might want to have an actual named over-ride file rather than a symlink. 

Does that allay your concerns any?

**Comment by kad** [comment]
Just as an idea: if --404file argument value starts with / (like "/404.html"), then it would look for file not in current directory but as global 404 page ?

**Comment by davidbilge** [comment]
@cortesi This would indeed solve the problem I described. But now, what if I use something like angular-cli or gulp serve to "host" my files already and this Webserver does not support wiring through a rest API or falling back to a default page. Then I would still need devd and I would also need a fallback behavior for one particular route, right? I'm just trying to point out that it might be more flexible to be able to configure a fallback/404 handler for each route. Or is this too contrived?

**Comment by cortesi** [comment]
@davidbilge Just to make sure I understand - in this scenario, we have two upstream servers we're reverse proxying to, and you'd like to replace 404 responses from one of them with the contents of a different request? I'm hesitant about this, because I feel that 404 replacement for reverse proxied traffic would be brittle, complicated and rarely used. The feature makes a lot more sense for local files that we serve, however. 

Thanks for taking the time to think through this with me.

**Comment by davidbilge** [comment]
I think you are right. Actually, angular-cli already seems to do the right thing when it comes to routes. Basically, when proxying a webserver, devd should rely on the webserver to behave correctly. When serving files, devd itself is the webserver, thus it should provide a means to resolve "file not found" problems.

**Comment by ThomasWeiser** [comment]
Any updates on this?

Some of my project are SPAs written in [Elm](http://elm-lang.org/) and I would like to do their routing without a hash sign in the URL. Any of the solutions discussed here would work.

Needless to say that I strongly prefer devd/modd, which works great for Elm development. No npm/webpack/whatnot clutter.

**Comment by cortesi** [comment]
@ThomasWeiser I think we have a clear design for this now. I don't have time to implement it right at the moment, but would gladly merge a patch. If I don't get an external contribution, I'll turn to this before the next release.

Here's the rough design that I think serves all the use cases:

- A --404file flag that specifies an over-ride when files are not found for static routes. Specifying an over-ride for a non-static route will be an error.
- The format for the flag is similar to a route specification:

        [hostpath=]404filepath

- If the 404filepath un-rooted or relative (e.g. "notfound.html", "./templates/notfound.html"), we will look for it up the tree to the base of the static directory
- If the 404filepath is rooted (e.g. "/notfound.html"), we will only look for the file at the exact path from the static directory base.

So, some examples of valid specifications would be:

For all static routes, look for the file "override.html" in all directories:

    --404file override.html

For all static routes, look for "override.html" only at the root:

    --404file /override.html

For only the app virtual domain (i.e. app.devd.io) look for "override.html":

    --404file app=override.html

**Comment by ThomasWeiser** [comment]
Great! Thank you very much!

Unfortunately I cannot contribute any golang programming.

**Comment by cortesi** [comment]
Could everyone interested in this ticket please take a look at the implementation I just pushed. The docs in the README explains it all.

One feature I'm thinking of adding here is to only serve an over-ride if its guessed MIME type matches the guessed MIME type of the request URL. That is, an over-ride that serves /index.html for all files not found will still return a 404 if the requested file was /foo.png, because the MIME types differ. Can anyone think of corner cases where this wouldn't work?

**Comment by cortesi** [comment]
Direct link to the docs:

https://github.com/cortesi/devd#serving-default-content-for-files-not-found

**Comment by davidbilge** [comment]
The documentation for the 404-feature sounds really good and seems flexible enough.

MIME type matching seems useful to avoid serving the index.html instead of, say, a .js file or the favicon.ico. The MIME type for a directory request would have to be "text/html" of course. This would certainly cover 99% of the use cases. What if someone uses xml + xslt (is that still a thing?) or another technology that does not send html files to the browser as a default? That's the only corner case I can come up with.

**Comment by ThomasWeiser** [comment]
This looks great! 

Will try it as soon as possible, which will unfortunately be not before Monday. Thank you!

**Comment by ThomasWeiser** [comment]
I have tested `--notfound` with my app in development. Works great, with one small limitation resulting from MIME type matching: The routes in our app are of the form `/user/some-name`, i.e. without a file extension and without a trailing slash. Seems to be the prevalent naming pattern for SPAs' routes.

I don't know what devd is guessing as the MIME type of `/user/some-name`, maybe `text/plain`, or maybe something else. But it certainly differs from `text/html`. So, `--notfound /index.html` has no effect here.

There is a simple workaround, using a filename without an extension like this:

```sh
ln -s index.html index
devd --notfound /index .
```

But, maybe devd could handle this special case in another way. Idea would be to match any unknown filetype in the URL with a default path of type `text/html`. I don't have much background in HTTP serving, so this solution may or may not feasible.

Then there is also a corner case, where the URL contains a dot that doesn't mark a file extension, like `user/thomas.weiser`. MIME guessing can completely go wrong here.

Another option coming to mind would be to extend the `--notfound` switch, like:

```sh
devd \
    --notfound /images=-
    --notfound /.==/index.html
    ...
```
The first switch would exclude the root `/images` from serving default content.
The second switch would turn off MIME checking for the root `/.`.
This would also work for the mentioned `user/thomas.weiser` case.
Certainly some better syntax than `=-` and `==` would be necessary.

**Comment by cortesi** [comment]
Excellent feedback, thanks. I've just changed the type matching to default to "text/html", unless we can positively establish otherwise. I think this covers off on pretty much all the issues you listed here. If possible, I'd like to get away without doing anything more complicated with the notfound routs - the routing situation in devd is already quite complex as it is.

**Comment by ThomasWeiser** [comment]
Totally understandable. Defaulting to "text/html" will be sufficient for most scenarios.

Applications that may have a dot in the last URL part have to use a workaround by including a trailing slash, like `/user/thomas.weiser/`. Otherwise it might be misinterpreted as a file extension (not in this example, but there are many file extensions which have some associated MIME type).

Thanks for the update! It makes _devd_ usable for many single page apps, which is a great thing!

**Comment by cortesi** [comment]
Yes, the corner case where this doesn't work is if you end with a known extension, and don't have a trailing slash - i.e. */user/thomas.png*. I think that's rare enough that we can expect developers to do a bit of extra work in this situation.

**Comment by ThomasWeiser** [comment]
Yes, totally agree.

Do you plan to release this as v0.7 in the near future, or do you work on other features to be included in this release? I'm asking because I would like to introduce devd to my co-worker without asking him to build devd on his own. Thanks again!

**Comment by cortesi** [comment]
I plan to release as soon as I have a few hours to spare, in the next few days.

**Comment by ThomasWeiser** [comment]
Great, thank you very much!
