### ISSUE TITLE
not reloading

### ISSUE THREAD

**Issue by x110dc** [cortesi/devd#48]
I'm trying to use `devd` to reload the page of a Django project, but it's not working. When I view the source I don't see the livereload JS being injected there. Am I doing something wrong? Here's my `modd.conf`:

```
/src/common/js/* {

    daemon: python manage.py runserver 0.0.0.0:8080
    daemon: ./devd --modd --address="0.0.0.0" --port=8000 http://localhost:8080

}
```

**Comment by cortesi** [comment]
Hi Daniel. Does the HTML returned from your app have a well-formed <head></head> section? This is where devd injects the livereload package, and if there is no head section it leaves the page intact.

**Comment by x110dc** [comment]
Thanks for responding. And so quickly! 

There's definitely a `<head>` section.

I tried with a different (Flask) app and it worked fine, injecting `<script src="/.devd.livereload.js"></script>` as expected. So it seems to be something specific to the Django project/HTML.   

If it helps you can see the HTML here: http://www.texastribune.org.

**Comment by cortesi** [comment]
Hey - so the issue here was that devd only looked for the closing </head> tag in the first 10k of the HTM - we need to draw the line somewhere so we can efficiently stream through larger files that don't need livereload. That site has an amazing amount of info in a script tag, which pushed it beyond this limit. I've just bumped the limit to 50k, so this is now "fixed" in master.

In the longer term, I might add a log warning if we can't find the closing head tag to make this more visible, and consider adjusting things to do the injection after the opening tag instead (though that's not quite as good for other reasons).

Thanks for reporting the issue!

**Comment by x110dc** [comment]
Thanks for "fixing" it!
